version: '3.4'
services:
  db:
    container_name: pr1_db
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./server:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
  web:
    build: ./server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./server:/var/www/html